spring:
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres?currentSchema=jdbc
    username:
    password:
  jpa:
    defer-datasource-initialization: true

#  h2:
#    console:
#      path: /h2-console
#      settings:
#        web-allow-others: true